import turtle
turtle.speed(100)
turtle.shape('turtle')
turtle.color('black')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(-40, 120)
turtle.pendown()
turtle.color('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 120)
turtle.pendown()
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(0, 80)
turtle.pendown()
turtle.width(7)
turtle.color('white')
turtle.goto(0, 120)
turtle.penup()
turtle.goto(-26, 50)
turtle.pendown()
turtle.color('red')
turtle.right(90)
for i in range(180):
    turtle.forward(0.5)
    turtle.left(1)
input()